config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :bikes, only: [:index, :new, :create, :show] do
    resources :bookings, only: [:create]
  end
  get "profile", to: "pages#profile", as: :profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :bike
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bikes, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  #before_action :set_user, only: %i[new create show edit update]

  def index
    @bikes = Bike.all
  end

  def new
    @bike = Bike.new
  end

  def create
    @bike = Bike.new(bike_params)
    @bike.user = current_user
    if @bike.save
      redirect_to bike_path(@bike)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @bike = Bike.find(params[:id])
    @booking = Booking.new
    # grâce à cette ligne,simple form est utilisée avec un "booking vide" %>
  end

  def edit
    @bike = Bike.find(params[:id])
  end

  def update
    @bike = Bike.find(params[:id])
    if @bike.update(bike_params)
      redirect_to bike_path(@bike)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @bike = Bike.find(params[:id])
    @bike.destroy
    redirect_to bikes_path
  end

  private

  def bike_params
    params.require(:bike).permit(:color, :price, :photo, :description, :name)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)
    @booking.starting_date = @booking.date_range.split(" to ")[0]
    @booking.ending_date = @booking.date_range.split(" to ")[1]
    @booking.user = current_user
    @bike = Bike.find(params[:bike_id])
    @booking.bike = @bike
    if @booking.save!
      redirect_to bike_path(@bike), notice: "Acceptée"
    else
      render 'bikes/show', status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:date_range)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def profile
    @user = current_user
    @bookings = @user.bookings
    @bikes = @user.bikes
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/_simple_form.html.erb
<%= simple_form_for [bike, booking] do |f| %>
  <%= f.input :date_range,
            as: :string,
            label: false,
            input_html: {
              data: { controller: "datepicker" },
              placeholder: "Click to select your reservation dates",
              style: "width: 305px; margin-left: 42px",
              class: "form-control custom-input"
            },
            class: "d-none" %>
  <%= f.submit class: "btn btn-primary rounded-3", style: "margin-left: 42px"%>
<% end %>

<%# on va utiliser flatpickr et ajouter la date selectionnée par l'User en f.input date debut et f.input date de fin %>

app/views/bikes/edit.html.erb
<div class="container">
  <h1>Edit a bike:</h1>
    <%= form_with model: @bike do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :price %>
      <%= f.number_field :price %>
      <%= f.submit %>
    <% end %>
</div>

app/views/bikes/index.html.erb
<h1 class="text-center"> 🚴‍♀️ Our rental bikes 🚴‍♀️ </h1>

<div class="bike-index-container">
  <% @bikes.each do |bike|%>
    <div class="bike-index-details">
      <%= cl_image_tag bike.photo.key, crop: :fill, class: "bike-index-img"%>
      <div class="bike-index-text">
        <p><strong><%= bike.name%></strong></p>
        <p> <%= bike.price%>€ </p>
        <p> <%= bike.shortd %></p>
      </div>
      <%=link_to "More details", bike_path(bike), style: "border-radius: 16px;", class: "btn btn-warning" %>
    </div>
  <% end %>
</div>

app/views/bikes/new.html.erb
<h1 class="new-title">🚲 Your bike 🚲 </h1>
  <div class="new-form" >
    <%= simple_form_for @bike do |f| %>
  <div class="form_text">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control text", placeholder: "Marcel"%>
  </div>

  <div class="form_description">
    <%= f.label :description%>
    <%= f.text_field :description, class: "form-control text", placeholder: "Fast, competent, reliable"%>
  </div>

  <div class="form_color">
    <%= f.label :color%>
    <%= f.text_field :color, class: "form-control text", placeholder: "Black"%>
  </div>

  <div class="form_price">
    <%= f.label :price %>
    <%= f.number_field :price, class: "form-control text", placeholder: "150" %>
  </div>

  <div class="form_photo">
    <%= f.input :photo, as: :file, class: "form-control text", placeholder: "Choose a picture"  %>
  </div>

    <%= f.submit value: "Add my bike", class: "btn btn-new rounded-3"%>
    <% end %>
</div>

app/views/bikes/show.html.erb
<p class="notice d-none" data-controller="sweetalert"><%= notice %></p>

<div class="mx-auto p-2">
  <%=link_to "Return to others bike", bikes_path(@bike), class: "btn btn-warning rounded-3", style: "margin-left: 34px"%>

  <div class= "grande div">
    <div class="container bg-white flexbox-space-between mt-3 custom-rounded box-shadowed">
      <div class="qassim col-6 d-flex justify-content-center align-items-center mr-3">
        <ul>
          <h3><strong><%= @bike.name %></strong></h3>
            <li> <img width="32" height="32" src="https://img.icons8.com/color/32/paint-palette.png" alt="paint-palette"/> <%= @bike.color %> </li>
            <li> <img width="32" height="32" src="https://img.icons8.com/external-kmg-design-outline-color-kmg-design/32/external-euro-money-kmg-design-outline-color-kmg-design-3.png" alt="external-euro-money-kmg-design-outline-color-kmg-design-3"/> <%= @bike.price %> € </li>
            <li> <img width="32" height="32" src="https://img.icons8.com/pulsar-color/32/user.png" alt="user"/> <%= @bike.user.name %> </li>
            <li> <img width="32" height="32" src="https://img.icons8.com/external-anggara-filled-outline-anggara-putra/32/external-about-bubble-chat-anggara-filled-outline-anggara-putra.png" alt="external-about-bubble-chat-anggara-filled-outline-anggara-putra"/> <%= @bike.description %> </li>
        </ul>
      </div>

      <div class="p-2 mt-1 mb-1">
        <%= cl_image_tag @bike.photo.key, height: 300, width: 400, crop: :fill, class: "custom-rounded", style: "border-radius: 5px;"%>
      </div>

    </div>
  </div>
</div>
<%= render "simple_form", booking: @booking, bike: @bike%>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light"  style="background-color:#edb616">
<div class="Slogan website mx-4" >
    <%= link_to "RentABike!", root_path, class: "navbar-brand" %>
  </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%# <li class="nav-item">
          <a class="nav-link" aria-current="page" href="#">Home</a>
        </li> %>
        <li class="nav-item">
          <%= link_to "See all the bikes", bikes_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Rent my bike", new_bike_path, class: "nav-link" %>
        </li>
      </ul>
        <div class="mx-3">
         <%= link_to "My Profile", profile_path , class: "btn btn-warning rounded-3" %>
        </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentABike</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Figtree:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <div class= "footer_down">
    <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<%# <h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p> %>

<div class="banner py-4" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= image_path('roues.jpg') %>'); background-repeat: no-repeat; height: 850px; background-size: cover; background-position: center; color: white;">
  <div class="container">
    <h1 class="text-white"> We provide <strong>professional bikes</strong> to <strong>athletes</strong> !</h1>
    <div class="py-2">
      <p class="text-white">Change your life and pick one of our bikes.</p>
      <%= link_to "Discover our bikes here", bikes_path , class: "btn btn-warning rounded-3 color: white" %>
    </div>
    <div class="py-4">
      <p>Gain a lot of money and rent one of your bikes.</p>
      <%= link_to "Rent your bike here", new_bike_path , class: "btn btn-warning rounded-3 color: white" %>
    </div>
  </div>
</div>
<%# <div style="height: 50vh"> %>
</div>

app/views/pages/profile.html.erb
<div class="container">
  <h1>Hello <%= current_user.name%>!👋</h1>
  <div class ="overview">
    <div class="cards">
      <h2>My bikes</h2>
        <% @bikes.each do |bike| %>
          <div class="card-product">
            <div class="card-product-img">
              <%= cl_image_tag bike.photo.key, style:"border-radius: 5px;"%>
            </div>
            <div class="card-product-info">
              <h3><strong><%= bike.name %></strong></h3>
              <p><%= bike.description%></p>
            </div>
          </div>
        <% end %>
    </div>
    <div class="cards">
      <h2>My bookings</h2>
        <% @bookings.each do |booking| %>
          <div class="card-product">
            <div class="card-product-img">
              <%= cl_image_tag booking.bike.photo.key, style:"border-radius: 5px;"%>
            </div>
            <div class="card-product-info">
              <h3><strong><%= booking.bike.name %></strong></h3>
              <p>from : <%= booking.starting_date %></p>
              <p>to : <%= booking.ending_date %></p>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Show d'un User</h1>